name: benjudy
favicon: null
layout_spectrum: 0.8947196819353849
typography_spectrum: 0.25648759794421494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.052559195552021265
  lightness: 0.1317853673826903
  saturation: 0.24041307577863336
  rhythmicContrast: 0.48830291628837585
purpose: []
